name: Release Artifacts

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  container:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.30/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

      - name: Log in to ghcr.io
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Determine version
        shell: bash
        run: echo "##[set-output name=version;]$(earthly --artifact +version/version version 2>&1; cat version)"
        id: determine_version

      - name: Determine tags
        shell: bash
        run: echo "##[set-output name=tags;]$(echo -n "${{ steps.determine_version.outputs.version }}" > tags; if [[ "${{ steps.extract_branch.outputs.branch }}" == "main" ]]; then echo ",latest" >> tags; cat tags; fi)"
        id: determine_tags

      - name: Build and push image
        run: |
          earthly --ci --push +image --tags=${{ steps.determine_tags.outputs.tags }} --save_cmd=SAVE_IMAGE_GHCR

  charts:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.30/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

      - name: Build chart
        run: |
            mkdir -p .cr-release-packages && earthly --artifact +chart/k8sss*.tgz .cr-release-packages/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
